version: '3'

volumes:
  local-registry:

networks:
  front-tier:
  back-tier:

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - local-registry:/var/lib/registry
    networks:
      - front-tier
      - back-tier
  concourse-db:
    image: postgres:9.5
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: concourse
      POSTGRES_PASSWORD: changeme
      PGDATA: /database
    networks:
      - back-tier

  concourse-web:
    image: concourse/concourse
    command: web
    depends_on: [concourse-db]
    ports:
      - "8080:8080"
    volumes:
      - "./keys/web:/concourse-keys"
    networks:
      - front-tier
      - back-tier
    environment:
      CONCOURSE_BASIC_AUTH_USERNAME: concourse
      CONCOURSE_BASIC_AUTH_PASSWORD: changeme
      CONCOURSE_EXTERNAL_URL: "http://10.33.101.57:8080"
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse
      CONCOURSE_POSTGRES_PASSWORD: changeme
      CONCOURSE_POSTGRES_DATABASE: concourse

  concourse-worker:
    image: concourse/concourse
    depends_on: [concourse-web]
    command: worker
    volumes:
      - "./keys/worker:/concourse-keys"
    environment:
      CONCOURSE_TSA_HOST: concourse-web
      CONCOURSE_GARDEN_DNS_SERVER: 8.8.8.8
    networks:
      - back-tier
      - front-tier
    privileged: true