# fly -t lite set-pipeline --config go_hello_pipeline.yml --pipeline hello
resource_types:
  - name: docker-image-resource
    privileged: true
    type: docker-image
    source:
      repository: concourse/docker-image-resource
      tag: latest

resources:
- name: source-code-hello-world
  type: git
  source:
    uri: https://github.com/Sispheor/concourse_demo.git
    branch: master

- name: docker-local-registry
  type: docker-image-resource
  source:
    repository: 10.33.101.57:5000/hello
    insecure_registries:
      - 10.33.101.57:5000


jobs:
  - name: Tests
    plan:
      - get: source-code-hello-world
      - task: task-test
        file: source-code-hello-world/ci/01-task-tests.yml
      - put: docker-local-registry
        params:
          build: source-code-hello-world/hello_go_api
          dockerfile: source-code-hello-world/hello_go_api/hello.run.dockerfile

